# Generated by Django 4.2.16 on 2024-12-17 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profissionais", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profissional",
            name="cpf",
            field=models.CharField(max_length=11, null=True, unique=True),
        ),
    ]
