# Generated by Django 4.2.16 on 2024-12-26 14:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profissionais", "0002_profissional_cpf"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profissional",
            options={
                "ordering": ["nome"],
                "verbose_name": "Profissional",
                "verbose_name_plural": "Profissionais",
            },
        ),
        migrations.AddField(
            model_name="profissional",
            name="data_contratacao",
            field=models.DateField(
                blank=True,
                help_text="Data de início do vínculo com a instituição (opcional).",
                null=True,
                verbose_name="Data de Contratação",
            ),
        ),
        migrations.AddField(
            model_name="profissional",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="E-mail de contato do profissional (opcional).",
                max_length=254,
                null=True,
                unique=True,
                verbose_name="E-mail",
            ),
        ),
        migrations.AlterField(
            model_name="profissional",
            name="cpf",
            field=models.CharField(
                blank=True,
                help_text="CPF do profissional (11 dígitos, apenas números).",
                max_length=11,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{11}$", message="O CPF deve conter exatamente 11 dígitos."
                    )
                ],
                verbose_name="CPF",
            ),
        ),
        migrations.AlterField(
            model_name="profissional",
            name="especialidade",
            field=models.CharField(
                help_text="Área de especialização do profissional.",
                max_length=100,
                verbose_name="Especialidade",
            ),
        ),
        migrations.AlterField(
            model_name="profissional",
            name="nome",
            field=models.CharField(
                help_text="Nome completo do profissional.",
                max_length=100,
                unique=True,
                verbose_name="Nome Completo",
            ),
        ),
        migrations.AlterField(
            model_name="profissional",
            name="telefone",
            field=models.CharField(
                help_text="Telefone do profissional, com DDD.",
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{10,15}$",
                        message="O telefone deve conter entre 10 a 15 dígitos.",
                    )
                ],
                verbose_name="Telefone",
            ),
        ),
    ]
