# Generated by Django 4.2.16 on 2025-01-01 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sala",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        help_text="Identificação única da sala.",
                        max_length=10,
                        unique=True,
                        verbose_name="Número da Sala",
                    ),
                ),
                (
                    "capacidade",
                    models.PositiveIntegerField(
                        help_text="Capacidade máxima da sala.",
                        verbose_name="Capacidade",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        blank=True,
                        help_text="Descrição opcional da sala.",
                        null=True,
                        verbose_name="Descrição",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sala",
                "verbose_name_plural": "Salas",
                "ordering": ["numero"],
            },
        ),
    ]
