# Generated by Django 4.2.16 on 2024-12-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pacientes", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paciente",
            options={
                "ordering": ["nome"],
                "verbose_name": "Paciente",
                "verbose_name_plural": "Pacientes",
            },
        ),
        migrations.RemoveField(
            model_name="paciente",
            name="idade",
        ),
        migrations.AlterField(
            model_name="paciente",
            name="data_nascimento",
            field=models.DateField(verbose_name="Data de Nascimento"),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="endereco",
            field=models.TextField(blank=True, null=True, verbose_name="Endereço"),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="nome",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Nome Completo"
            ),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="telefone",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Telefone"
            ),
        ),
    ]
