# Generated by Django 4.2.16 on 2025-01-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pacientes", "0002_alter_paciente_options_remove_paciente_idade_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paciente",
            name="data_nascimento",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de Nascimento"
            ),
        ),
    ]
