# Generated by Django 4.2.16 on 2024-12-26 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pacientes", "0002_alter_paciente_options_remove_paciente_idade_and_more"),
        ("profissionais", "0003_alter_profissional_options_and_more"),
        ("agendamentos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Procedimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nome do Procedimento"
                    ),
                ),
                (
                    "descricao",
                    models.TextField(verbose_name="Descrição do Procedimento"),
                ),
                (
                    "preco",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Preço"
                    ),
                ),
            ],
            options={
                "verbose_name": "Procedimento",
                "verbose_name_plural": "Procedimentos",
            },
        ),
        migrations.CreateModel(
            name="Sala",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="Número da Sala"
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        blank=True, null=True, verbose_name="Descrição da Sala"
                    ),
                ),
            ],
            options={
                "verbose_name": "Sala",
                "verbose_name_plural": "Salas",
            },
        ),
        migrations.AlterField(
            model_name="agendamento",
            name="cor",
            field=models.CharField(
                default="#3788d8", max_length=7, verbose_name="Cor do Evento"
            ),
        ),
        migrations.AlterField(
            model_name="agendamento",
            name="data_fim",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data de Término"
            ),
        ),
        migrations.AlterField(
            model_name="agendamento",
            name="data_inicio",
            field=models.DateTimeField(verbose_name="Data de Início"),
        ),
        migrations.AlterField(
            model_name="agendamento",
            name="descricao",
            field=models.TextField(blank=True, default="", verbose_name="Descrição"),
        ),
        migrations.AlterField(
            model_name="agendamento",
            name="paciente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agendamentos",
                to="pacientes.paciente",
                verbose_name="Paciente",
            ),
        ),
        migrations.AlterField(
            model_name="agendamento",
            name="profissional",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agendamentos",
                to="profissionais.profissional",
                verbose_name="Profissional",
            ),
        ),
        migrations.AddField(
            model_name="agendamento",
            name="procedimento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agendamentos",
                to="agendamentos.procedimento",
                verbose_name="Procedimento",
            ),
        ),
        migrations.AddField(
            model_name="agendamento",
            name="sala",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agendamentos",
                to="agendamentos.sala",
                verbose_name="Sala",
            ),
        ),
    ]
