# Generated by Django 4.2.16 on 2025-01-04 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("salas", "0001_initial"),
        ("procedimentos", "0001_initial"),
        ("agendamentos", "0002_procedimento_sala_alter_agendamento_cor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agendamento",
            name="procedimento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agendamentos",
                to="procedimentos.procedimento",
                verbose_name="Procedimento",
            ),
        ),
        migrations.AlterField(
            model_name="agendamento",
            name="sala",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agendamentos",
                to="salas.sala",
                verbose_name="Sala",
            ),
        ),
        migrations.DeleteModel(
            name="Procedimento",
        ),
        migrations.DeleteModel(
            name="Sala",
        ),
    ]
